# Generated by Django 4.0.2 on 2022-05-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_rename_bought_at_order_price_cart_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Appli', 'Appliances'), ('Apps ', 'Apps & Games'), ('Arts,', 'Arts, Crafts, & Sewing'), ('Autom', 'Automotive Parts & Accessories'), ('Baby', 'Baby'), ('Beaut', 'Beauty & Personal Care'), ('Books', 'Books'), ('CDs &', 'CDs & Vinyl'), ('Cell ', 'Cell Phones & Accessories'), ('Cloth', 'Clothing, Shoes and Jewelry'), ('Colle', 'Collectibles & Fine Art'), ('Compu', 'Computers'), ('Elect', 'Electronics'), ('Garde', 'Garden & Outdoor'), ('Groce', 'Grocery & Gourmet Food'), ('Handm', 'Handmade'), ('Healt', 'Health, Household & Baby Care'), ('Home ', 'Home & Kitchen'), ('Indus', 'Industrial & Scientific'), ('Lugga', 'Luggage & Travel Gear'), ('Movie', 'Movies & TV'), ('Music', 'Musical Instruments'), ('Offic', 'Office Products'), ('Pet S', 'Pet Supplies'), ('Sport', 'Sports & Outdoors'), ('Tools', 'Tools & Home Improvement'), ('Toys ', 'Toys & Games'), ('Video', 'Video Games')], default=('Cloth', 'Clothing, Shoes and Jewelry'), max_length=50),
            preserve_default=False,
        ),
    ]
