# Generated by Django 4.0.2 on 2022-05-24 17:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, max_digits=8)),
                ('measure_type', models.CharField(choices=[('mm', 'millimeter'), ('cm', 'centimeter'), ('m', 'meter')], max_length=100)),
                ('model_no', models.CharField(max_length=50)),
                ('release_date', models.DateField(default=datetime.datetime.today)),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='ecommerce.product')),
            ],
        ),
    ]
