# Generated by Django 4.0.2 on 2022-05-28 11:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_productfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='country_of_origin',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspecification',
            name='expiry_date',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='ecommerce.product'),
        ),
    ]
