# Generated by Django 4.0.2 on 2022-05-28 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
